In [1]:
print("Hello, MongoDB!")

Hello, MongoDB!

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("covid19_global_statistics_2026.csv")

In [4]:
data

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Europe,UK,68497907.0,2026-02-16,NaN,0.0,363666.0,24910387,NaN,3389.0,232112.0,7628357.0,522526476.0
234,Europe,Russia,145805947.0,2026-02-16,NaN,175641.0,165454.0,24124215,NaN,2762.0,402756.0,1875095.0,273400000.0
235,Asia,Turkey,85561976.0,2026-02-16,NaN,NaN,201399.0,17232066,NaN,1194.0,102174.0,1902052.0,162743369.0
236,Oceania,Australia,26068792.0,2026-02-16,NaN,8716.0,454687.0,11853144,NaN,937.0,24414.0,3142326.0,81916639.0
237,Asia,Vietnam,98953541.0,2026-02-16,NaN,941018.0,117481.0,11625195,NaN,437.0,43206.0,867342.0,85826548.0

In [5]:
data.head()

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
0,Africa,Eritrea,3662244.0,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0
1,Africa,Niger,26083660.0,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0
2,Africa,Saint-Helena,6115.0,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN
3,South-America,Falkland-Islands,3539.0,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0
4,North-America,Montserrat,4965.0,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0

In [6]:
data.tail()

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests
233,Europe,UK,68497907.0,2026-02-16,NaN,0.0,363666.0,24910387,NaN,3389.0,232112.0,7628357.0,522526476.0
234,Europe,Russia,145805947.0,2026-02-16,NaN,175641.0,165454.0,24124215,NaN,2762.0,402756.0,1875095.0,273400000.0
235,Asia,Turkey,85561976.0,2026-02-16,NaN,NaN,201399.0,17232066,NaN,1194.0,102174.0,1902052.0,162743369.0
236,Oceania,Australia,26068792.0,2026-02-16,NaN,8716.0,454687.0,11853144,NaN,937.0,24414.0,3142326.0,81916639.0
237,Asia,Vietnam,98953541.0,2026-02-16,NaN,941018.0,117481.0,11625195,NaN,437.0,43206.0,867342.0,85826548.0

In [7]:
data.shape

(238, 13)

In [8]:
data.columns

Index(['continent', 'country', 'population', 'date', 'new_cases',
       'active_cases', 'cases_per_million', 'total_cases', 'new_deaths',
       'deaths_per_million', 'total_deaths', 'tests_per_million',
       'total_tests'],
      dtype='str')

In [9]:
type(data)

pandas.DataFrame

In [10]:
data_dict = data.to_dict(orient="records")

In [11]:
data_dict

[{'continent': 'Africa',
  'country': 'Eritrea',
  'population': 3662244.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 2782.0,
  'total_cases': 10189,
  'new_deaths': nan,
  'deaths_per_million': 28.0,
  'total_deaths': 103.0,
  'tests_per_million': 6470.0,
  'total_tests': 23693.0},
 {'continent': 'Africa',
  'country': 'Niger',
  'population': 26083660.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 729.0,
  'cases_per_million': 381.0,
  'total_cases': 9931,
  'new_deaths': nan,
  'deaths_per_million': 12.0,
  'total_deaths': 312.0,
  'tests_per_million': 9759.0,
  'total_tests': 254538.0},
 {'continent': 'Africa',
  'country': 'Saint-Helena',
  'population': 6115.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 2164.0,
  'cases_per_million': 354211.0,
  'total_cases': 2166,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': nan,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'South-America',
  'country': 'Falkland-Islands',
  'population': 3539.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 545352.0,
  'total_cases': 1930,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': nan,
  'tests_per_million': 2439107.0,
  'total_tests': 8632.0},
 {'continent': 'North-America',
  'country': 'Montserrat',
  'population': 4965.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 19.0,
  'cases_per_million': 282578.0,
  'total_cases': 1403,
  'new_deaths': nan,
  'deaths_per_million': 1611.0,
  'total_deaths': 8.0,
  'tests_per_million': 3577442.0,
  'total_tests': 17762.0},
 {'continent': nan,
  'country': 'Diamond-Princess',
  'population': nan,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': nan,
  'total_cases': 712,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': 13.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Europe',
  'country': 'Vatican-City',
  'population': 799.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 36295.0,
  'total_cases': 29,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': nan,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Africa',
  'country': 'Western-Sahara',
  'population': 626161.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 16.0,
  'total_cases': 10,
  'new_deaths': nan,
  'deaths_per_million': 2.0,
  'total_deaths': 1.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': nan,
  'country': 'MS-Zaandam',
  'population': nan,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': nan,
  'total_cases': 9,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': 2.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Asia',
  'country': 'China',
  'population': 1448471400.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 118977.0,
  'cases_per_million': 347.0,
  'total_cases': 503302,
  'new_deaths': nan,
  'deaths_per_million': 4.0,
  'total_deaths': 5272.0,
  'tests_per_million': 110461.0,
  'total_tests': 160000000.0},
 {'continent': 'Africa',
  'country': 'Liberia',
  'population': 5305117.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 12.0,
  'cases_per_million': 1525.0,
  'total_cases': 8090,
  'new_deaths': nan,
  'deaths_per_million': 56.0,
  'total_deaths': 295.0,
  'tests_per_million': 26356.0,
  'total_tests': 139824.0},
 {'continent': 'Oceania',
  'country': 'Nauru',
  'population': 10903.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 45.0,
  'cases_per_million': 494635.0,
  'total_cases': 5393,
  'new_deaths': nan,
  'deaths_per_million': 92.0,
  'total_deaths': 1.0,
  'tests_per_million': 1881042.0,
  'total_tests': 20509.0},
 {'continent': 'North-America',
  'country': 'Caribbean-Netherlands',
  'population': 26647.0,
  'date': '2026-02-16',
  'new_cases': 3.0,
  'active_cases': 1168.0,
  'cases_per_million': 438398.0,
  'total_cases': 11682,
  'new_deaths': nan,
  'deaths_per_million': 1426.0,
  'total_deaths': 38.0,
  'tests_per_million': 1130559.0,
  'total_tests': 30126.0},
 {'continent': 'Africa',
  'country': 'Comoros',
  'population': 907419.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 9.0,
  'cases_per_million': 10038.0,
  'total_cases': 9109,
  'new_deaths': nan,
  'deaths_per_million': 177.0,
  'total_deaths': 161.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Africa',
  'country': 'Guinea-Bissau',
  'population': 2063367.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 508.0,
  'cases_per_million': 4659.0,
  'total_cases': 9614,
  'new_deaths': nan,
  'deaths_per_million': 86.0,
  'total_deaths': 177.0,
  'tests_per_million': 70385.0,
  'total_tests': 145231.0},
 {'continent': 'Africa',
  'country': 'Chad',
  'population': 17413580.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 2633.0,
  'cases_per_million': 442.0,
  'total_cases': 7701,
  'new_deaths': nan,
  'deaths_per_million': 11.0,
  'total_deaths': 194.0,
  'tests_per_million': 10988.0,
  'total_tests': 191341.0},
 {'continent': 'North-America',
  'country': 'Sint-Maarten',
  'population': 43966.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 54.0,
  'cases_per_million': 251353.0,
  'total_cases': 11051,
  'new_deaths': nan,
  'deaths_per_million': 2093.0,
  'total_deaths': 92.0,
  'tests_per_million': 1411454.0,
  'total_tests': 62056.0},
 {'continent': 'Oceania',
  'country': 'Wallis-and-Futuna',
  'population': 10982.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 3104.0,
  'cases_per_million': 323256.0,
  'total_cases': 3550,
  'new_deaths': nan,
  'deaths_per_million': 728.0,
  'total_deaths': 8.0,
  'tests_per_million': 1867419.0,
  'total_tests': 20508.0},
 {'continent': 'North-America',
  'country': 'St-Barth',
  'population': 9945.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 553746.0,
  'total_cases': 5507,
  'new_deaths': nan,
  'deaths_per_million': 603.0,
  'total_deaths': 6.0,
  'tests_per_million': 7908095.0,
  'total_tests': 78646.0},
 {'continent': 'North-America',
  'country': 'Saint-Kitts-and-Nevis',
  'population': 53871.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 122645.0,
  'total_cases': 6607,
  'new_deaths': nan,
  'deaths_per_million': 891.0,
  'total_deaths': 48.0,
  'tests_per_million': 2356704.0,
  'total_tests': 126958.0},
 {'continent': 'Oceania',
  'country': 'Tokelau',
  'population': 1378.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 80.0,
  'cases_per_million': 58055.0,
  'total_cases': 80,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': nan,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Oceania',
  'country': 'Kiribati',
  'population': 123419.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 2358.0,
  'cases_per_million': 41201.0,
  'total_cases': 5085,
  'new_deaths': nan,
  'deaths_per_million': 194.0,
  'total_deaths': 24.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'North-America',
  'country': 'St-Vincent-Grenadines',
  'population': 111551.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 57.0,
  'cases_per_million': 86723.0,
  'total_cases': 9674,
  'new_deaths': nan,
  'deaths_per_million': 1112.0,
  'total_deaths': 124.0,
  'tests_per_million': 1023720.0,
  'total_tests': 114197.0},
 {'continent': 'North-America',
  'country': 'Antigua-and-Barbuda',
  'population': 99509.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 6.0,
  'cases_per_million': 91509.0,
  'total_cases': 9106,
  'new_deaths': nan,
  'deaths_per_million': 1467.0,
  'total_deaths': 146.0,
  'tests_per_million': 189943.0,
  'total_tests': 18901.0},
 {'continent': 'Africa',
  'country': 'Sierra-Leone',
  'population': 8306436.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 937.0,
  'total_cases': 7779,
  'new_deaths': nan,
  'deaths_per_million': 15.0,
  'total_deaths': 126.0,
  'tests_per_million': 31296.0,
  'total_tests': 259958.0},
 {'continent': 'North-America',
  'country': 'British-Virgin-Islands',
  'population': 30596.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 241600.0,
  'total_cases': 7392,
  'new_deaths': nan,
  'deaths_per_million': 2092.0,
  'total_deaths': 64.0,
  'tests_per_million': 3508269.0,
  'total_tests': 107339.0},
 {'continent': 'Oceania',
  'country': 'Cook-Islands',
  'population': 17571.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 51.0,
  'cases_per_million': 409937.0,
  'total_cases': 7203,
  'new_deaths': nan,
  'deaths_per_million': 114.0,
  'total_deaths': 2.0,
  'tests_per_million': 1120596.0,
  'total_tests': 19690.0},
 {'continent': 'Africa',
  'country': 'Sao-Tome-and-Principe',
  'population': 227679.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 13.0,
  'cases_per_million': 29770.0,
  'total_cases': 6778,
  'new_deaths': nan,
  'deaths_per_million': 351.0,
  'total_deaths': 80.0,
  'tests_per_million': 130008.0,
  'total_tests': 29600.0},
 {'continent': 'North-America',
  'country': 'Turks-and-Caicos',
  'population': 39741.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 3.0,
  'cases_per_million': 169900.0,
  'total_cases': 6752,
  'new_deaths': nan,
  'deaths_per_million': 1007.0,
  'total_deaths': 40.0,
  'tests_per_million': 15520193.0,
  'total_tests': 616788.0},
 {'continent': 'Oceania',
  'country': 'Palau',
  'population': 18233.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 4.0,
  'cases_per_million': 344979.0,
  'total_cases': 6290,
  'new_deaths': nan,
  'deaths_per_million': 548.0,
  'total_deaths': 10.0,
  'tests_per_million': 3917841.0,
  'total_tests': 71434.0},
 {'continent': 'North-America',
  'country': 'Anguilla',
  'population': 15230.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 256336.0,
  'total_cases': 3904,
  'new_deaths': nan,
  'deaths_per_million': 788.0,
  'total_deaths': 12.0,
  'tests_per_million': 3373736.0,
  'total_tests': 51382.0},
 {'continent': 'North-America',
  'country': 'Saint-Pierre-Miquelon',
  'population': 5759.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 1001.0,
  'cases_per_million': 599410.0,
  'total_cases': 3452,
  'new_deaths': nan,
  'deaths_per_million': 347.0,
  'total_deaths': 2.0,
  'tests_per_million': 4410488.0,
  'total_tests': 25400.0},
 {'continent': 'Oceania',
  'country': 'Tuvalu',
  'population': 12066.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 243909.0,
  'total_cases': 2943,
  'new_deaths': nan,
  'deaths_per_million': 83.0,
  'total_deaths': 1.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Oceania',
  'country': 'Niue',
  'population': 1622.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 3.0,
  'cases_per_million': 652898.0,
  'total_cases': 1059,
  'new_deaths': nan,
  'deaths_per_million': nan,
  'total_deaths': nan,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'North-America',
  'country': 'Cayman-Islands',
  'population': 67277.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 22882.0,
  'cases_per_million': 467797.0,
  'total_cases': 31472,
  'new_deaths': nan,
  'deaths_per_million': 550.0,
  'total_deaths': 37.0,
  'tests_per_million': 3311280.0,
  'total_tests': 222773.0},
 {'continent': 'Africa',
  'country': 'Congo',
  'population': 5797805.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 983.0,
  'cases_per_million': 4377.0,
  'total_cases': 25375,
  'new_deaths': nan,
  'deaths_per_million': 67.0,
  'total_deaths': 386.0,
  'tests_per_million': 59991.0,
  'total_tests': 347815.0},
 {'continent': 'North-America',
  'country': 'Nicaragua',
  'population': 6779100.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 14041.0,
  'cases_per_million': 2728.0,
  'total_cases': 18491,
  'new_deaths': nan,
  'deaths_per_million': 33.0,
  'total_deaths': 225.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Asia',
  'country': 'Tajikistan',
  'population': 9957464.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 397.0,
  'cases_per_million': 1786.0,
  'total_cases': 17786,
  'new_deaths': nan,
  'deaths_per_million': 13.0,
  'total_deaths': 125.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Africa',
  'country': 'Djibouti',
  'population': 1016097.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 74.0,
  'cases_per_million': 15441.0,
  'total_cases': 15690,
  'new_deaths': nan,
  'deaths_per_million': 186.0,
  'total_deaths': 189.0,
  'tests_per_million': 301094.0,
  'total_tests': 305941.0},
 {'continent': 'North-America',
  'country': 'Greenland',
  'population': 56973.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 9189.0,
  'cases_per_million': 210117.0,
  'total_cases': 11971,
  'new_deaths': nan,
  'deaths_per_million': 369.0,
  'total_deaths': 21.0,
  'tests_per_million': 2894810.0,
  'total_tests': 164926.0},
 {'continent': 'Africa',
  'country': 'Equatorial-Guinea',
  'population': 1496662.0,
  'date': '2026-02-16',
  'new_cases': 7.0,
  'active_cases': 139.0,
  'cases_per_million': 11512.0,
  'total_cases': 17229,
  'new_deaths': nan,
  'deaths_per_million': 122.0,
  'total_deaths': 183.0,
  'tests_per_million': 244342.0,
  'total_tests': 365697.0},
 {'continent': 'Africa',
  'country': 'Somalia',
  'population': 16841795.0,
  'date': '2026-02-16',
  'new_cases': 10.0,
  'active_cases': 12791.0,
  'cases_per_million': 1623.0,
  'total_cases': 27334,
  'new_deaths': nan,
  'deaths_per_million': 81.0,
  'total_deaths': 1361.0,
  'tests_per_million': 23778.0,
  'total_tests': 400466.0},
 {'continent': 'North-America',
  'country': 'Bermuda',
  'population': 61939.0,
  'date': '2026-02-16',
  'new_cases': 11.0,
  'active_cases': 10.0,
  'cases_per_million': 304493.0,
  'total_cases': 18860,
  'new_deaths': 2.0,
  'deaths_per_million': 2664.0,
  'total_deaths': 165.0,
  'tests_per_million': 16622128.0,
  'total_tests': 1029558.0},
 {'continent': 'Africa',
  'country': 'Gambia',
  'population': 2558482.0,
  'date': '2026-02-16',
  'new_cases': 28.0,
  'active_cases': 65.0,
  'cases_per_million': 4935.0,
  'total_cases': 12626,
  'new_deaths': nan,
  'deaths_per_million': 145.0,
  'total_deaths': 372.0,
  'tests_per_million': 60851.0,
  'total_tests': 155686.0},
 {'continent': 'North-America',
  'country': 'Grenada',
  'population': 113475.0,
  'date': '2026-02-16',
  'new_cases': 10.0,
  'active_cases': 97.0,
  'cases_per_million': 173545.0,
  'total_cases': 19693,
  'new_deaths': nan,
  'deaths_per_million': 2097.0,
  'total_deaths': 238.0,
  'tests_per_million': 1612523.0,
  'total_tests': 182981.0},
 {'continent': 'Oceania',
  'country': 'Vanuatu',
  'population': 321832.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 29.0,
  'cases_per_million': 37346.0,
  'total_cases': 12019,
  'new_deaths': nan,
  'deaths_per_million': 44.0,
  'total_deaths': 14.0,
  'tests_per_million': 77606.0,
  'total_tests': 24976.0},
 {'continent': 'Asia',
  'country': 'Timor-Leste',
  'population': 1369429.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 220.0,
  'cases_per_million': 17131.0,
  'total_cases': 23460,
  'new_deaths': nan,
  'deaths_per_million': 101.0,
  'total_deaths': 138.0,
  'tests_per_million': 203391.0,
  'total_tests': 278529.0},
 {'continent': 'Africa',
  'country': 'Lesotho',
  'population': 2175699.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 9435.0,
  'cases_per_million': 16610.0,
  'total_cases': 36138,
  'new_deaths': nan,
  'deaths_per_million': 332.0,
  'total_deaths': 723.0,
  'tests_per_million': 198199.0,
  'total_tests': 431221.0},
 {'continent': 'North-America',
  'country': 'Haiti',
  'population': 11680283.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 73.0,
  'cases_per_million': 2968.0,
  'total_cases': 34667,
  'new_deaths': nan,
  'deaths_per_million': 74.0,
  'total_deaths': 860.0,
  'tests_per_million': 11337.0,
  'total_tests': 132422.0},
 {'continent': 'Europe',
  'country': 'Faeroe-Islands',
  'population': 49233.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 703959.0,
  'total_cases': 34658,
  'new_deaths': nan,
  'deaths_per_million': 569.0,
  'total_deaths': 28.0,
  'tests_per_million': 15802409.0,
  'total_tests': 778000.0},
 {'continent': 'Africa',
  'country': 'Mali',
  'population': 21473764.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 89.0,
  'cases_per_million': 1544.0,
  'total_cases': 33164,
  'new_deaths': nan,
  'deaths_per_million': 35.0,
  'total_deaths': 743.0,
  'tests_per_million': 37483.0,
  'total_tests': 804909.0},
 {'continent': 'North-America',
  'country': 'Saint-Lucia',
  'population': 185113.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 0.0,
  'cases_per_million': 163225.0,
  'total_cases': 30215,
  'new_deaths': nan,
  'deaths_per_million': 2215.0,
  'total_deaths': 410.0,
  'tests_per_million': 1139752.0,
  'total_tests': 210983.0},
 {'continent': 'Africa',
  'country': 'Benin',
  'population': 12784726.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 26.0,
  'cases_per_million': 2193.0,
  'total_cases': 28036,
  'new_deaths': nan,
  'deaths_per_million': 13.0,
  'total_deaths': 163.0,
  'tests_per_million': 47268.0,
  'total_tests': 604310.0},
 {'continent': 'Asia',
  'country': 'Macao',
  'population': 667490.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 24063.0,
  'cases_per_million': 41458.0,
  'total_cases': 27673,
  'new_deaths': nan,
  'deaths_per_million': 184.0,
  'total_deaths': 123.0,
  'tests_per_million': 11760.0,
  'total_tests': 7850.0},
 {'continent': 'Oceania',
  'country': 'Micronesia',
  'population': 117489.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 225953.0,
  'total_cases': 26547,
  'new_deaths': nan,
  'deaths_per_million': 553.0,
  'total_deaths': 65.0,
  'tests_per_million': 701598.0,
  'total_tests': 82430.0},
 {'continent': 'Europe',
  'country': 'San-Marino',
  'population': 34085.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 46.0,
  'cases_per_million': 768226.0,
  'total_cases': 26185,
  'new_deaths': nan,
  'deaths_per_million': 3755.0,
  'total_deaths': 128.0,
  'tests_per_million': 5775414.0,
  'total_tests': 196855.0},
 {'continent': 'Oceania',
  'country': 'Solomon-Islands',
  'population': 721159.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 35989.0,
  'total_cases': 25954,
  'new_deaths': nan,
  'deaths_per_million': 276.0,
  'total_deaths': 199.0,
  'tests_per_million': nan,
  'total_tests': nan},
 {'continent': 'Africa',
  'country': 'Burkina-Faso',
  'population': 22102838.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': 118.0,
  'cases_per_million': 1001.0,
  'total_cases': 22114,
  'new_deaths': nan,
  'deaths_per_million': 18.0,
  'total_deaths': 400.0,
  'tests_per_million': 11265.0,
  'total_tests': 248995.0},
 {'continent': 'Europe',
  'country': 'Liechtenstein',
  'population': 38387.0,
  'date': '2026-02-16',
  'new_cases': nan,
  'active_cases': nan,
  'cases_per_million': 562013.0,
  'total_cases': 21574,
  'new_deaths': nan,
  'deaths_per_million': 2449.0,
  'total_deaths': 94.0,
  'tests_per_million': 2929559.0,
  'total_tests': 112457.0},

In [ ]:
DB_NAME = "covid19_db"
COLLECTION_NAME = "covid19_collection"
COLLECTION_URL = "<mongoDB connection_string goes here>"

In [16]:
import pymongo

client = pymongo.MongoClient(COLLECTION_URL)
database = client[DB_NAME]
collection = database[COLLECTION_NAME]

## Storing Data in MongoDB

In [17]:
records = collection.insert_many(data_dict)

AutoReconnect: SSL handshake failed: ac-hzmplqy-shard-00-01.d0j2cx3.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: connectTimeoutMS: 20000.0ms)

## Fetching Data from MongoDB

In [22]:
records = collection.find()

In [23]:
records

In [24]:
for record in records:
    print(record)

AutoReconnect: SSL handshake failed: ac-hzmplqy-shard-00-01.d0j2cx3.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:992) (configured timeouts: connectTimeoutMS: 20000.0ms)